### ISSUE TITLE
Talk Proposal - Synchro Labs

### ISSUE THREAD

**Issue by BobDickinson** [seanode/meetup#2]
> As a local Node-focussed startup, we would really appreciate the opportunity to present to your membership.  Given that we are a commercial entity with a non-open-source product, I'm not sure we fit exactly, but hoping so.
# Building Native Mobile Apps with Node.js

The Synchro mobile application development platform allows enterprise developers to quickly and easily build apps that present to end users as native mobile apps, but where all of the app code actually runs on
a Node.js server.   The resulting apps are easier to create, easier to integrate, easier to update, and more secure than other cross platform app platforms.  And everything is based on Node.js.

This talk will briefly cover the architecture of the Synchro platform and will then dive in to creating a mobile app live (we will install the server tools, create an app, install the Synchro Explorer mobile client, and demonstrate the app we created - all in about 10 minutes).  The target would be to keep this talk to about 20 minutes, with another 10 minutes for Q&A.

I have been a software developer for 25 years, with several periods of also being a founder or executive.  Three of the startups that I founded have had successful exits.  I am a enterprise developer, a full-stack web developer, and a native mobile developer (iOS, Android, Windows).  I've been working with Node.js for the past three years.

Synchro Labs, Inc. is a Redmond area startup.  We were a sponsor of the [Node Interactive](http://events.linuxfoundation.org/events/archive/2015/node-interactive) event in Portland last December.

Bob Dickinson
Twitter: [@SynchroLabs](https://twitter.com/synchrolabs)
GitHub: @BobDickinson / @SynchroLabs
http://synchro.io

**Comment by hamoore** [comment]
This looks great! Thank you! We will get back to you soon!

**Comment by hamoore** [comment]
Hi Bob! Do you think you'd be interested in giving this talk in June?

**Comment by BobDickinson** [comment]
That would be great!

**Comment by hamoore** [comment]
Awesome! We generally like Wednesdays... what does your availability look like? Are Wednesdays okay/do you have any date preferences?

**Comment by BobDickinson** [comment]
We're open all Wednesdays in June.  The sooner the better.

**Comment by hamoore** [comment]
How does June 22nd sound? :)

**Comment by BobDickinson** [comment]
Sounds great!

**Comment by BobDickinson** [comment]
Are we confirmed for June 22nd?

**Comment by hamoore** [comment]
Hi Bob! Yes, we are! :)

**Comment by scottnonnenberg** [comment]
http://www.meetup.com/Seattle-Node-js/events/231696353/
