### ISSUE TITLE
Talk Proposal - Koa.js: A happy path to async/await

### ISSUE THREAD

**Issue by cmgriffing** [seanode/meetup#3]
# Koa.js: A happy path to async/await

Brief description:
With the future of Express uncertain, a lot of people are looking for another framework to take its place. There are numerous options to choose from with the top 2 being Hapi.js and Koa.js. I'm not going to claim one is better than the other because the Hapi ecosystem is awesome and thriving. However, I do think Koa provides an easier upgrade path to async/await once it is supported in Node.

[Blog post](http://chrisgriffing.com/coding/javascript/2016/03/14/koa-js-a-happy-path-to-async-await/)
[Slides (WIP)](http://cmgriffing.github.io/gens2aa/slides/segmented/#/)
The slides are a bit bare of text at times, so I have included notes that can be seen in the presenter popup window from this version of the link: [http://cmgriffing.github.io/gens2aa/slides/segmented/?notes=true#/](http://cmgriffing.github.io/gens2aa/slides/segmented/?notes=true#/)

Bio:
I am a full stack developer in Bellevue at Fresh Consulting. I think there are probably people much more qualified than me to give a presentation on this topic but I have started using Koa in side projects and I really like it. I think others might benefit from the easy async/await migration path it provides.
- Chris Griffing
- [GitHub](https://github.com/cmgriffing)
- [Website](http://chrisgriffing.com)

Full disclosure: I have a slide of citations but I wanted to call it out here as well. I am using code snippets from [https://www.promisejs.org/generators](https://www.promisejs.org/generators/) to help explain the way promises can be wrapped by generators. I also am using snippets from that same author's presentation on the subject. This is done because the explanation of generators and async/await is to properly inform the audience before diving into my original content of koa.js being an easy migration path.

I also want to point out that I am completely open to feedback and changing the presentation slide structure.

**Comment by hamoore** [comment]
We think this looks great! Would you be able to give this talk on 5/18 or 5/25?

**Comment by cmgriffing** [comment]
Awesome. Yes, I can speak at the May meetup.
In the coming weeks, I will be fine-tuning the slide structure and I may reach out here on this issue for some feedback.

Thanks.

**Comment by hamoore** [comment]
@cmgriffing Do you have a short bio that I can include in promo for the event? Would you prefer I just put the first line of your bio from above?

**Comment by cmgriffing** [comment]
@hamoore I think the first sentence pretty much sums it up but I can try and come up with something a bit more fun:
"... a full stack developer at Fresh Consulting in Bellevue. His hobbies include snowboarding, golfing, and going to meetups. Some say that his beanie is physically attached to his scalp."

Just the one sentence would be fine too. If you would like me to try and come up with some more serious extra details, I can.

**Comment by hamoore** [comment]
@cmgriffing That looks great- thanks! :)

**Comment by hamoore** [comment]
@cmgriffing Also, we just received confirmation from or host/sponsor, Madrona, for Wednesday, May 25th.

**Comment by cmgriffing** [comment]
@hamoore Awesome. Thanks.

**Comment by scottnonnenberg** [comment]
http://www.meetup.com/Seattle-Node-js/events/230745855/
