### ISSUE TITLE
ECMAScript Modules: Fury Road

### ISSUE THREAD

**Issue by jdalton** [seanode/meetup#7]
# ECMAScript Modules: Fury Road

![](https://cloud.githubusercontent.com/assets/4303/26185711/736a63a4-3b41-11e7-8998-2432b0493bfc.png)

Years after the collapse of io.js, the Node Core Technical Committee (CTC)  has decreed that the .MJS file extension is required for ECMAScript modules (ESM), leaving fans of .JS trapped with CommonJS. Will a code warrior emerge to save the day? Tune in to find out.

* John-David Dalton
* [Twitter](https://twitter.com/jdalton)
* [GitHub](https://github.com/jdalton)
* [Website](https://lodash.com/)

**Comment by ryan-roemer** [comment]
Fantastic. I heard through the grapevine that this talk might be in the works, and I can't wait to hear it!

Next week, I'm going to start putting together venue and sponsors for potential dates. Offhand, I'm thinking maybe Wed, 6/14 or Wed, 6/21 -- how's your June availability looking?

**Comment by jdalton** [comment]
My June is available 😄

**Comment by ryan-roemer** [comment]
Hi @jdalton ! Can you email me at `ryan.roemer@formidable.com` or DM me on twitter at https://twitter.com/ryan_roemer to coordinate logistics? We've got a potential host lined up!
